version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wave_app
    ports:
      - "8082:8000"
    volumes:
      - .:/var/www
    networks:
      - wave_network
    environment:
      DB_HOST: 192.168.100.2  # Point to the external database server
      DB_PORT: 4987           # Default MySQL port
      DB_USER: root           # Database user, adjust as necessary
      DB_PASSWORD: ikhode  # Database password, adjust as necessary
      DB_NAME: community   

networks:
  wave_network:
    driver: bridge

volumes:
  db_data:
