version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wave_app
    ports:
      - "8082:8000"
    volumes:
      - .:/var/www
    networks:
      - wave_network


  db:
    image: mysql:5.7
    container_name: wave_db
    user: "${UID}:${GID}"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wave
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wave_network

networks:
  wave_network:
    driver: bridge

volumes:
  db_data:
